CREATE DATABASE IF NOT EXISTS keygap;
USE keygap;

CREATE TABLE IF NOT EXISTS rounds (
    id VARCHAR(36) PRIMARY KEY,
    text_content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS scores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    wpm INT NOT NULL,
    accuracy INT NOT NULL,
    duration INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
